### ISSUE TITLE
 Couldn't find or read configuration file.

### ISSUE THREAD

**Issue by irag** [FrancoisSchnell/GPicSync#16]
I've been using this for months and then a week ago this started happening where I get the message: "Couldn't find or read configuration file" in the status window.  I searched the repository and can't find anything that might generate this message.

**Comment by irag** [comment]
I copied the configuration file from master into the runtime folder and that got rid of the message about the configuration file but it still hangs and when I exit, I am told to look at the log file which contains the following:
Unhandled exception in thread started by <function sync at 0x031C1930>
Traceback (most recent call last):
  File "gpicsync-GUI.py", line 718, in sync
  File "gpicsync.pyc", line 44, in __init__
  File "gpx.pyc", line 68, in extract
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by irag** [comment]
It seems the error is in my trackpoint file.  I used an older one and it processes though since there is no time sync, every picture fails.
